AWSTemplateFormatVersion: 2010-09-09
Description: Elasticsearch-dev
Parameters:
  ElasticsearchDomainName:
    Type: String
    AllowedPattern: '[a-z][a-z0-9]*'
    Description: Name of Elasticsearch domain for log [a-z][a-z0-9]*
Resources:
  ElasticsearchDomain:
    Type: AWS::Elasticsearch::Domain
    Properties:
      DomainName: !Sub "${ElasticsearchDomainName}"
      ElasticSearchVersion: "6.7"
      ElasticSearchClusterConfig: 
        InstanceCount: 1
        InstanceType: "t2.micro"
      EBSOptions: 
        EBSEnabled: true
        Iops: 0
        VolumeSize: 10
        VolumeType: "gp2"
      SnapshotOptions: 
        AutomatedSnapshotStartHour: 0
      AccessPolicies: 
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::621467334954}:root"
            Action: "es:*"
            Resource: !Sub "arn:aws:es:${AWS::Region}:${AWS::621467334954}:domain/${ElasticsearchDomainName}/*"

